export const REPEATABLE_JOB_ID = "REPEATABLE_JOB_ID"
export const REPEATABLE_JOB_NAME = "REPEATABLE_JOB_NAME"

export const REPEATABLE_BESTBUY_JOB_NAME = "REPEATABLE_BESTBUY_JOB_NAME"
export const REPEATABLE_HARRODS_JOB_NAME = "REPEATABLE_HARRODS_JOB_NAME"
